### ISSUE TITLE
Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by mdemenko** [marcdacz/compare-pdf#18]
Error: ENOENT: no such file or directory, open 'C:\VSTS\1\_work\2\s\automation/testdata/pdf/baselinePngs/expected Report/expected Report-1.png'

    at Object.openSync (fs.js:498:3)
    at Object.writeFileSync (fs.js:1524:35)
    at pdfPageToPng (C:\VSTS\1\_work\2\s\automation\node_modules\compare-pdf\functions\engines\native.js:25:6)
    at Object.pdfToPng (C:\VSTS\1\_work\2\s\automation\node_modules\compare-pdf\functions\engines\native.js:42:4)
    at C:\VSTS\1\_work\2\s\automation\node_modules\compare-pdf\functions\compareImages.js:58:4

**Comment by mdemenko** [comment]
It was my issue with tests setup. Closed the ticket.
