### ISSUE TITLE
Error while installing `compare-pdf` | Node Version: `v21.5.0` | Platform: macOS Sonoma v14.2.1

### ISSUE THREAD

**Issue by ankita21gaikwad** [marcdacz/compare-pdf#42]
## Problem Statement: 
   getting below error when installing `compare-pdf`. Node Version: `v21.5.0` | Platform: macOS Sonoma v14.2.1

npm WARN deprecated dommatrix@1.0.3: dommatrix is no longer maintained. Please use @thednp/dommatrix.
npm ERR! code 1
npm ERR! path /AquaProjects/comparing-utility/node_modules/canvas
npm ERR! command failed
npm ERR! command sh -c node-pre-gyp install --fallback-to-build --update-binary
npm ERR! Failed to execute '/opt/homebrew/Cellar/node/21.5.0/bin/node /opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --update-binary --module=AquaProjects/comparing-utility/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=AquaProjects/comparing-utility/node_modules/canvas/build/Release --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v120' (1)
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@1.0.11
npm ERR! node-pre-gyp info using node@21.5.0 | darwin | arm64
npm ERR! (node:10899) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
npm ERR! (Use `node --trace-deprecation ...` to show where the warning was created)
npm ERR! node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v120-darwin-unknown-arm64.tar.gz
npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v120-darwin-unknown-arm64.tar.gz 
npm ERR! node-pre-gyp WARN Pre-built binaries not installable for canvas@2.11.2 and node@21.5.0 (node-v120 ABI, unknown) (falling back to source compile with node-gyp) 
npm ERR! node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v120-darwin-unknown-arm64.tar.gz 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@10.0.1
npm ERR! gyp info using node@21.5.0 | darwin | arm64
npm ERR! gyp info ok 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@10.0.1
npm ERR! gyp info using node@21.5.0 | darwin | arm64
npm ERR! gyp info find Python using Python version 3.9.6 found at "/Library/Developer/CommandLineTools/usr/bin/python3"
npm ERR! gyp info spawn /Library/Developer/CommandLineTools/usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args '/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args 'binding.gyp',
npm ERR! gyp info spawn args '-f',
npm ERR! gyp info spawn args 'make',
npm ERR! gyp info spawn args '-I',
npm ERR! gyp info spawn args '/AquaProjects/comparing-utility/node_modules/canvas/build/config.gypi',
npm ERR! gyp info spawn args '-I',
npm ERR! gyp info spawn args '/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args '-I',
npm ERR! gyp info spawn args '/Library/Caches/node-gyp/21.5.0/include/node/common.gypi',
npm ERR! gyp info spawn args '-Dlibrary=shared_library',
npm ERR! gyp info spawn args '-Dvisibility=default',
npm ERR! gyp info spawn args '-Dnode_root_dir=/Library/Caches/node-gyp/21.5.0',
npm ERR! gyp info spawn args '-Dnode_gyp_dir=/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args '-Dnode_lib_file=/Library/Caches/node-gyp/21.5.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args '-Dmodule_root_dir=/AquaProjects/comparing-utility/node_modules/canvas',
npm ERR! gyp info spawn args '-Dnode_engine=v8',
npm ERR! gyp info spawn args '--depth=.',
npm ERR! gyp info spawn args '--no-parallel',
npm ERR! gyp info spawn args '--generator-output',
npm ERR! gyp info spawn args 'build',
npm ERR! gyp info spawn args '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! /bin/sh: pkg-config: command not found
npm ERR! gyp: Call to 'pkg-config pixman-1 --libs' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack at ChildProcess.<anonymous> (/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:271:18)
npm ERR! gyp ERR! stack at ChildProcess.emit (node:events:519:28)
npm ERR! gyp ERR! stack at ChildProcess._handle.onexit (node:internal/child_process:294:12)
npm ERR! gyp ERR! System Darwin 23.2.0
npm ERR! gyp ERR! command "/opt/homebrew/Cellar/node/21.5.0/bin/node" "/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--update-binary" "--module=/AquaProjects/comparing-utility/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/AquaProjects/comparing-utility/node_modules/canvas/build/Release" "--napi_version=9" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v120"
npm ERR! gyp ERR! cwd /AquaProjects/comparing-utility/node_modules/canvas
npm ERR! gyp ERR! node -v v21.5.0
npm ERR! gyp ERR! node-gyp -v v10.0.1
npm ERR! gyp ERR! not ok 
npm ERR! node-pre-gyp ERR! build error 
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute '/opt/homebrew/Cellar/node/21.5.0/bin/node /opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --update-binary --module=/AquaProjects/comparing-utility/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/AquaProjects/comparing-utility/node_modules/canvas/build/Release --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v120' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/AquaProjects/comparing-utility/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:519:28)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1105:16)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:305:5)
npm ERR! node-pre-gyp ERR! System Darwin 23.2.0
npm ERR! node-pre-gyp ERR! command "/opt/homebrew/Cellar/node/21.5.0/bin/node" "/AquaProjects/comparing-utility/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--update-binary"
npm ERR! node-pre-gyp ERR! cwd /AquaProjects/comparing-utility/node_modules/canvas
npm ERR! node-pre-gyp ERR! node -v v21.5.0
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.11
npm ERR! node-pre-gyp ERR! not ok

npm ERR! A complete log of this run can be found in: /.npm/_logs/2024-01-25T12_17_48_986Z-debug-0.log

**Comment by Dutchie1990** [comment]
Same error

**Comment by vietnux** [comment]
same

**Comment by Dutchie1990** [comment]
Please try 

```
brew install zeromq
brew install pkgconfig
```

**Comment by Dutchie1990** [comment]
if that doesn't work as well also downgrade python to:

```Python 3.12.1```

**Comment by vietnux** [comment]
my python version is 3.11.4

**Comment by Dutchie1990** [comment]
What about: 

```
brew install pkg-config cairo pango libpng jpeg giflib
```

did'nt solve the problem?

**Comment by vietnux** [comment]
> What about:
> 
> ```
> brew install pkg-config cairo pango libpng jpeg giflib
> ```
> 
> did'nt solve the problem?

thank you so much!
i installed lib

**Comment by yuvarajpm1853** [comment]
I faced same issue where I used nodejs version 22.18.0

Solution: 

Downgrade your nodejs version to 20.18.0 . Then , try installing compare-pdf .

**Comment by akotsin** [comment]
Rolling back to an older Node.js version is not the best long-term solution. Technologies evolve, and runtimes inevitably reach end of support. For example, Node.js 20 already has a defined deprecation timeline in AWS Lambda ([Apr 30, 2026](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html)), after which new function creation and updates will eventually be blocked.

The root cause here appears to be that the package depends on an older 2.x version of canvas. For newer Node.js versions (e.g., 22+ on macOS arm64), there are no prebuilt binaries available for that ABI, so the installation falls back to building from source, which then fails due to missing native dependencies. Starting from version 3.x, canvas migrated to N-API, making it ABI-stable across Node.js versions. This removes the need for per-Node-version prebuilt binaries (as required in 2.x) and significantly reduces these installation issues.

As a temporary workaround, using Node.js 22+ together with the following override works:

```json
"overrides": {
  "canvas": "^3.2.0"
}
```

@marcdacz I really like this package and appreciate the work behind it. To ensure it continues working smoothly out of the box with modern Node.js versions, releasing a new version with updated dependencies would likely be the most sustainable solution. This would help users avoid similar problems in the future.

<img width="574" height="42" alt="Image" src="https://github.com/user-attachments/assets/a38af6a0-0b7f-4a9a-bc26-a9fafbd59524" />

~~I tested this approach and have not encountered any issues so far.~~

**UPD**: I noticed that the amount of memory being used has increased significantly. I ran the following tests by executing the same code that compares two PDFs under different environments:

- **Node.js 20 (canvas 2.x)**
```bash
[memory] {
  rss: '2130 MB',
  heapTotal: '392 MB',
  heapUsed: '347 MB',
  external: '1258 MB',
  arrayBuffers: '1244 MB'
}
```

- **Node.js 20 (override canvas 3.x)**
```bash
[memory] {
  rss: '3083 MB',
  heapTotal: '393 MB',
  heapUsed: '347 MB',
  external: '1209 MB',
  arrayBuffers: '1196 MB'
}
```

- **Node.js 24 (override canvas 3.x)**
```bash
[memory] {
  rss: '4306 MB',
  heapTotal: '483 MB',
  heapUsed: '349 MB',
  external: '1239 MB',
  arrayBuffers: '1227 MB'
}
```

The increase in memory consumption is quite significant.

**Comment by akotsin** [comment]
I also ran a couple more comparative tests. To fully confirm my theory, I created a clean project where only a single comparison of two identical 313-page PDF files is performed. Here are the results.

- **Node.js 20 (canvas 2.x)**
 
<img width="850" height="957" alt="Image" src="https://github.com/user-attachments/assets/106df0fe-95b0-46e6-a14a-7017c3f3a5f6" />

- **Node.js 20 (override canvas 3.x)**

<img width="743" height="855" alt="Image" src="https://github.com/user-attachments/assets/cdddaa5c-93d9-4672-be4f-418e2723a8b0" />

- **Node.js 24 (override canvas 3.x)**

<img width="750" height="829" alt="Image" src="https://github.com/user-attachments/assets/1aaaeb72-8d71-4d59-9d09-2251cd862ab8" />

As you can see, upgrading canvas from version 2.x to 3.x caused a global increase in memory usage. And on top of that, updating Node.js added even more.

**Comment by akotsin** [comment]
If you're interested, over the past couple of days I decided to completely rethink the PDF comparison approach. That resulted in this [new package](https://www.npmjs.com/package/pdf-pixel-diff) (pdf-pixel-diff).

Functionally, it’s quite similar to compare-pdf, but it offers significantly more capabilities — especially with the option:

```ts
compare: {
    combineImages: true,
}
```

<img width="1340" height="579" alt="Image" src="https://github.com/user-attachments/assets/667bd756-4c51-45b1-a139-3e793b534a7a" />

Memory consumption on identical files is 20x lower, since there is no canvas dependency involved.

<img width="1728" height="582" alt="Image" src="https://github.com/user-attachments/assets/d2f06307-bb06-4408-aa83-3f62e118c360" />
